/*
Author: Darian
Date Modified: March 20, 2017
IDE: Netbeans 8.2
Program: Calculates price before and after tax of a fast food order
File: GUI and logic
 */
package fastfood;

import java.text.DecimalFormat;

/**
 *
 * @author Meep3_000
 */
public class Main extends javax.swing.JFrame {
    
    float priceBurger = 2.49f;//Burger price
    float priceFries = 1.89f;//
    float priceDrink = 0.99f;
    float hst = 0.13f;
    DecimalFormat moneyFormat;
    
    /**
     * Creates new form Main
     */
    public Main() {
        moneyFormat = new DecimalFormat("$#0.00");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        burgersLabel = new javax.swing.JLabel();
        friesLabel = new javax.swing.JLabel();
        drinksLabel = new javax.swing.JLabel();
        burgersField = new javax.swing.JTextField();
        friesField = new javax.swing.JTextField();
        drinksField = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        subtotalField = new javax.swing.JTextField();
        taxLabel = new javax.swing.JLabel();
        taxField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        tenderedLabel = new javax.swing.JLabel();
        tenderedField = new javax.swing.JTextField();
        changeLabel = new javax.swing.JLabel();
        changeField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        enterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Fast Food Priculator");

        java.awt.GridBagLayout contentPanelLayout = new java.awt.GridBagLayout();
        contentPanelLayout.columnWidths = new int[] {100, 100};
        contentPanelLayout.rowHeights = new int[] {30, 30, 30, 30, 30, 30};
        contentPanel.setLayout(contentPanelLayout);

        burgersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        burgersLabel.setText("Number of Burgers:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(burgersLabel, gridBagConstraints);

        friesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friesLabel.setText("Number of Fries:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(friesLabel, gridBagConstraints);

        drinksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        drinksLabel.setText("Number of Drinks:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(drinksLabel, gridBagConstraints);

        burgersField.setMinimumSize(new java.awt.Dimension(60, 20));
        burgersField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        contentPanel.add(burgersField, gridBagConstraints);

        friesField.setMinimumSize(new java.awt.Dimension(60, 20));
        friesField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        contentPanel.add(friesField, gridBagConstraints);

        drinksField.setMinimumSize(new java.awt.Dimension(60, 20));
        drinksField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        contentPanel.add(drinksField, gridBagConstraints);

        subtotalLabel.setText("Subtotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        contentPanel.add(subtotalLabel, gridBagConstraints);

        subtotalField.setEditable(false);
        subtotalField.setMinimumSize(new java.awt.Dimension(60, 20));
        subtotalField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        contentPanel.add(subtotalField, gridBagConstraints);

        taxLabel.setText("Tax (HST at 13%):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        contentPanel.add(taxLabel, gridBagConstraints);

        taxField.setEditable(false);
        taxField.setMinimumSize(new java.awt.Dimension(60, 20));
        taxField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        contentPanel.add(taxField, gridBagConstraints);

        totalLabel.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        contentPanel.add(totalLabel, gridBagConstraints);

        totalField.setEditable(false);
        totalField.setMinimumSize(new java.awt.Dimension(60, 20));
        totalField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        contentPanel.add(totalField, gridBagConstraints);

        tenderedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenderedLabel.setText("Tendered (without $):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(tenderedLabel, gridBagConstraints);

        tenderedField.setMinimumSize(new java.awt.Dimension(60, 20));
        tenderedField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        contentPanel.add(tenderedField, gridBagConstraints);

        changeLabel.setText("Change:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        contentPanel.add(changeLabel, gridBagConstraints);

        changeField.setEditable(false);
        changeField.setMinimumSize(new java.awt.Dimension(60, 20));
        changeField.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        contentPanel.add(changeField, gridBagConstraints);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {100, 100};
        jPanel1.setLayout(jPanel1Layout);

        enterButton.setText("Enter");
        enterButton.setAlignmentX(0.5F);
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 162, 7, 179);
        jPanel1.add(enterButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    I'll have 2 number 9s,
    a number 9 large,
    a number 7 with extra dip,
    2 number 45s, one with cheese,
    and a large soda
    */
    
    
    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        float subtotal = 0.0f;
        int burgers, fries, drinks;
        float tendered;
        try{
            burgers = Integer.parseInt(burgersField.getText());//Get values in fields
            fries = Integer.parseInt(friesField.getText());
            drinks = Integer.parseInt(drinksField.getText());
            if(tenderedField.getText().length() > 0){//Set tendered amount to amount in field or zero
                tendered = Float.parseFloat(tenderedField.getText());
            }else tendered = 0;
        }catch(Exception e){//Catch exceptions
            new ErrorDialog(e).setVisible(true);
            return;
        }
        subtotal += burgers * priceBurger;//Calculate total price of food
        subtotal += fries * priceFries;
        subtotal += drinks * priceDrink;
        subtotalField.setText(moneyFormat.format(subtotal));//Display subtotal
        float tax = subtotal * hst;//Calculate tax
        taxField.setText(moneyFormat.format(tax));//Display tax
        float total = subtotal + tax;//Calculate total
        totalField.setText(moneyFormat.format(total));//Display total
        float change = tendered - total;
        String changeString = moneyFormat.format(change);
        if("-$0.00".equals(changeString)) changeString = "$0.00";//Avoid -$0.00 issue when using exact change
        changeField.setText(changeString);
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField burgersField;
    private javax.swing.JLabel burgersLabel;
    private javax.swing.JTextField changeField;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTextField drinksField;
    private javax.swing.JLabel drinksLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField friesField;
    private javax.swing.JLabel friesLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField subtotalField;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField taxField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField tenderedField;
    private javax.swing.JLabel tenderedLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
